flowchart LR
  %% DFD Level 1: 1. Запись к специалисту (логическая)
  E1[Пациент]
  P1[1.0 Запись к специалисту]
  D1[(D1 Справочник пациентов)]
  D2[(D2 Журнал записей)]

  E1 -- Заявка/PII [TLS] --> P1
  P1 -- Поиск/проверка [RBAC, Audit] --> D1
  P1 -- Создать/обновить [RBAC, Encrypt-at-Rest, Audit] --> D2
  P1 -- Подтверждение [No PII] --> E1
