flowchart LR
  %% DFD Level 1: 8. Внутренняя почта (логическая)
  E10[Сотрудники]
  E8[Exchange Mail Server]
  P8[8.0 Пересылка данных по почте]
  D3[(D3 Папки/файлы пациента)]
  D5[(D5 1С: Бухгалтерия)]
  D6[(D6 1С: Торговля и склад)]

  E10 -- Письма/вложения (PII/медданные) [DLP, S/MIME] --> P8
  P8 <--> E8
  P8 -- Сохранение/извлечение вложений [Encrypt-at-Rest, DLP] --> D3
  P8 -- Экспорт/импорт документов [Audit] --> D5
  P8 -- Экспорт/импорт документов [Audit] --> D6
