flowchart LR
  %% DFD Level 1: 6. Медкарта и файлы пациента (логическая)
  E3[Врач]
  P6[6.0 Ведение медкарты]
  D2[(D2 Журнал записей)]
  D3[(D3 Папка пациента на файловом сервере)]

  E3 -- Медзапись/заключение [RBAC] --> P6
  P6 -- Запись результатов/вложения [Encrypt-at-Rest, Audit] --> D3
  P6 -- Просмотр/коррекция графика [RBAC] --> D2
  P6 -- Доступ к документам [ABAC] --> E3
