flowchart LR
  %% DFD Level 1: 7. Обмен с лабораторией (логическая)
  E7[Лаборатория]
  P7[7.0 Обмен результатами анализов]
  D7[(D7 Реестр анализов за день)]
  D8[(D8 Результаты анализов)]
  D3[(D3 Папка пациента на файловом сервере)]

  D7 -- Передать реестр [mTLS, MinFields] --> P7
  P7 -- Реестр в работу [Audit] --> E7
  E7 -- Результаты по реестру [mTLS, Encrypt] --> D8
  P7 -- Сохранение результатов [Encrypt-at-Rest, RBAC] --> D3
