flowchart LR
  %% DFD Level 1: 2. Регистрация пациента (логическая)
  E1[Пациент]
  E2[Ресепшен]
  P2[2.0 Регистрация пациента]
  D1[(D1 Справочник пациентов)]
  D3[(D3 Папка пациента на файловом сервере)]

  E1 -- PII (ФИО, ДР, контакты) [TLS, Consent] --> P2
  E2 -- Инициировать регистрацию [RBAC] --> P2
  P2 -- Создать карточку [RBAC, Encrypt-at-Rest, Audit] --> D1
  P2 -- Создать структуру папки [Encrypt-at-Rest, AccessCtrl] --> D3
  P2 -- Скан договоров/согласий [DLP, Encrypt] --> D3
  P2 -- Уведомление [No PII] --> E2
