flowchart LR
  %% DFD Level 1: 5. Учёт ТМЦ (логическая)
  E6[Склад]
  P5[5.0 Учёт ТМЦ]
  D6[(D6 1С: Торговля и склад)]
  D5[(D5 1С: Бухгалтерия)]

  E6 -- Приход/расход [RBAC] --> P5
  P5 -- Движение ТМЦ [Audit] --> D6
  P5 -- Выгрузка проводок [Secure Channel] --> D5
  P5 -- Остатки/отчёты [No PII] --> E6
