flowchart LR
  %% DFD Level 1: 3. Принятие оплаты (логическая)
  E1[Пациент]
  E4[Кассир]
  E9[ККМ]
  P3[3.0 Принятие оплаты]
  D4[(D4 Excel-учёт кассы)]
  D5[(D5 1С: Бухгалтерия)]

  E1 -- Оплата услуги [POS Security] --> P3
  E4 -- Инициация продажи [RBAC] --> P3
  P3 -- Продажа/чек [Signed] --> E9
  E9 -- Сведения об оплате [Secure Channel] --> D5
  P3 -- Ведомость/экспорт кассы [AccessCtrl, Audit] --> D4
  P3 -- Подтверждение оплаты [No PII] --> E1
